// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/rikeshs/translationloader/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CacheDriver is an autogenerated mock type for the CacheDriver type
type CacheDriver struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, key
func (_m *CacheDriver) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Load provides a mock function with given fields: ctx, key, ttl, loader
func (_m *CacheDriver) Load(ctx context.Context, key string, ttl time.Duration, loader func(context.Context) (map[string]domain.Translations, error)) (map[string]domain.Translations, error) {
	ret := _m.Called(ctx, key, ttl, loader)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 map[string]domain.Translations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, func(context.Context) (map[string]domain.Translations, error)) (map[string]domain.Translations, error)); ok {
		return rf(ctx, key, ttl, loader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, func(context.Context) (map[string]domain.Translations, error)) map[string]domain.Translations); ok {
		r0 = rf(ctx, key, ttl, loader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.Translations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration, func(context.Context) (map[string]domain.Translations, error)) error); ok {
		r1 = rf(ctx, key, ttl, loader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCacheDriver creates a new instance of CacheDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheDriver {
	mock := &CacheDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
