// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/rikeshs/translationloader/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// TranslationLoader is an autogenerated mock type for the TranslationLoader type
type TranslationLoader struct {
	mock.Mock
}

// BulkLoad provides a mock function with given fields: ctx, entityIDs, locales
func (_m *TranslationLoader) BulkLoad(ctx context.Context, entityIDs []string, locales []string) (map[string]domain.Translations, error) {
	ret := _m.Called(ctx, entityIDs, locales)

	if len(ret) == 0 {
		panic("no return value specified for BulkLoad")
	}

	var r0 map[string]domain.Translations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) (map[string]domain.Translations, error)); ok {
		return rf(ctx, entityIDs, locales)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) map[string]domain.Translations); ok {
		r0 = rf(ctx, entityIDs, locales)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.Translations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = rf(ctx, entityIDs, locales)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTranslationLoader creates a new instance of TranslationLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTranslationLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *TranslationLoader {
	mock := &TranslationLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
