// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/rikeshs/translationloader/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// DocumentBuilder is an autogenerated mock type for the DocumentBuilder type
type DocumentBuilder struct {
	mock.Mock
}

// BuildProductDocument provides a mock function with given fields: ctx, p, attrs, specs, locales
func (_m *DocumentBuilder) BuildProductDocument(ctx context.Context, p domain.Product, attrs []domain.Attribute, specs []domain.ProductSpecification, locales []string) (domain.ProductDocument, error) {
	ret := _m.Called(ctx, p, attrs, specs, locales)

	if len(ret) == 0 {
		panic("no return value specified for BuildProductDocument")
	}

	var r0 domain.ProductDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Product, []domain.Attribute, []domain.ProductSpecification, []string) (domain.ProductDocument, error)); ok {
		return rf(ctx, p, attrs, specs, locales)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Product, []domain.Attribute, []domain.ProductSpecification, []string) domain.ProductDocument); ok {
		r0 = rf(ctx, p, attrs, specs, locales)
	} else {
		r0 = ret.Get(0).(domain.ProductDocument)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Product, []domain.Attribute, []domain.ProductSpecification, []string) error); ok {
		r1 = rf(ctx, p, attrs, specs, locales)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDocumentBuilder creates a new instance of DocumentBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocumentBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentBuilder {
	mock := &DocumentBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
